// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<NostrKeys> generateKeys() =>
    RustLib.instance.api.crateApiNostrGenerateKeys();

Future<String> getPublicKeyFromPrivate({required String privateKey}) => RustLib
    .instance
    .api
    .crateApiNostrGetPublicKeyFromPrivate(privateKey: privateKey);

Future<String> nip04Encrypt({
  required String plaintext,
  required String publicKey,
  required String privateKey,
}) => RustLib.instance.api.crateApiNostrNip04Encrypt(
  plaintext: plaintext,
  publicKey: publicKey,
  privateKey: privateKey,
);

Future<String> nip04Decrypt({
  required String ciphertext,
  required String publicKey,
  required String privateKey,
}) => RustLib.instance.api.crateApiNostrNip04Decrypt(
  ciphertext: ciphertext,
  publicKey: publicKey,
  privateKey: privateKey,
);

Future<String> nip44Encrypt({
  required String plaintext,
  required String publicKey,
  required String privateKey,
}) => RustLib.instance.api.crateApiNostrNip44Encrypt(
  plaintext: plaintext,
  publicKey: publicKey,
  privateKey: privateKey,
);

Future<String> nip44Decrypt({
  required String ciphertext,
  required String publicKey,
  required String privateKey,
}) => RustLib.instance.api.crateApiNostrNip44Decrypt(
  ciphertext: ciphertext,
  publicKey: publicKey,
  privateKey: privateKey,
);

Future<String> signEvent({
  required String eventJson,
  required String privateKey,
}) => RustLib.instance.api.crateApiNostrSignEvent(
  eventJson: eventJson,
  privateKey: privateKey,
);

Future<bool> verifyEvent({required NostrEvent event}) =>
    RustLib.instance.api.crateApiNostrVerifyEvent(event: event);

/// Encrypt private key using NIP-49 (ncryptsec1)
///
/// # Arguments
/// * `private_key` - Private key in hex format (64 characters)
/// * `password` - Password for encryption
/// * `log_n` - Scrypt log2(N) parameter (12-22, default 16)
/// * `key_security` - Key security level: 0=Weak, 1=Medium, 2=Unknown (default)
Future<String> nip49Encrypt({
  required String privateKey,
  required String password,
  int? logN,
  int? keySecurity,
}) => RustLib.instance.api.crateApiNostrNip49Encrypt(
  privateKey: privateKey,
  password: password,
  logN: logN,
  keySecurity: keySecurity,
);

/// Decrypt private key from NIP-49 (ncryptsec1) format
///
/// # Arguments
/// * `ncryptsec` - Encrypted private key in ncryptsec1 format
/// * `password` - Password for decryption
Future<String> nip49Decrypt({
  required String ncryptsec,
  required String password,
}) => RustLib.instance.api.crateApiNostrNip49Decrypt(
  ncryptsec: ncryptsec,
  password: password,
);

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiNostrGreet(name: name);

class NostrEvent {
  final String id;
  final String pubkey;
  final BigInt createdAt;
  final BigInt kind;
  final List<List<String>> tags;
  final String content;
  final String sig;

  const NostrEvent({
    required this.id,
    required this.pubkey,
    required this.createdAt,
    required this.kind,
    required this.tags,
    required this.content,
    required this.sig,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pubkey.hashCode ^
      createdAt.hashCode ^
      kind.hashCode ^
      tags.hashCode ^
      content.hashCode ^
      sig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pubkey == other.pubkey &&
          createdAt == other.createdAt &&
          kind == other.kind &&
          tags == other.tags &&
          content == other.content &&
          sig == other.sig;
}

class NostrKeys {
  final String publicKey;
  final String privateKey;

  const NostrKeys({required this.publicKey, required this.privateKey});

  @override
  int get hashCode => publicKey.hashCode ^ privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrKeys &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          privateKey == other.privateKey;
}
