// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_runtime_in_thread`, `handle_tls_connection`, `load_cert_chain`, `load_private_key`
// These types are ignored because they are not used by any `pub` functions: `TlsProxyRuntime`

/// Start TLS proxy server
///
/// This function starts a TLS proxy server that listens on `tls_port` for WSS connections
/// and forwards them to the local WS relay on `ws_port`.
///
/// The server uses `fullchain_pem` and `private_key_pem` which should contain the complete
/// certificate chain (server cert + intermediate certs) in the correct order.
///
/// # Arguments
/// * `host` - IP address to bind to (e.g., "127.0.0.1" or "0.0.0.0"). Use "127.0.0.1" on iOS to avoid iCloud Private Relay conflicts.
/// * `tls_port` - Port to listen for WSS connections (e.g., 28443)
/// * `ws_port` - Port of the local WS relay to forward to (e.g., 8081)
/// * `fullchain_pem` - Full certificate chain in PEM format (as string)
/// * `private_key_pem` - Private key in PEM format (as string)
void tlsProxyStart({
  required String host,
  required int tlsPort,
  required int wsPort,
  required String fullchainPem,
  required String privateKeyPem,
}) => RustLib.instance.api.crateApiTlsProxyTlsProxyStart(
  host: host,
  tlsPort: tlsPort,
  wsPort: wsPort,
  fullchainPem: fullchainPem,
  privateKeyPem: privateKeyPem,
);

/// Stop TLS proxy server
void tlsProxyStop() => RustLib.instance.api.crateApiTlsProxyTlsProxyStop();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TlsProxyServer>>
abstract class TlsProxyServer implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new TLS proxy server
  ///
  /// # Arguments
  /// * `host` - IP address to bind to (e.g., "127.0.0.1" or "0.0.0.0")
  /// * `tls_port` - Port to listen for WSS connections
  /// * `ws_port` - Port of the local WS relay to forward to
  /// * `fullchain_pem_path` - Path to fullchain.pem (contains server cert + intermediate certs)
  /// * `private_key_path` - Path to private key file
  static Future<TlsProxyServer> newInstance({
    required String host,
    required int tlsPort,
    required int wsPort,
    required String fullchainPemPath,
    required String privateKeyPath,
  }) => RustLib.instance.api.crateApiTlsProxyTlsProxyServerNew(
    host: host,
    tlsPort: tlsPort,
    wsPort: wsPort,
    fullchainPemPath: fullchainPemPath,
    privateKeyPath: privateKeyPath,
  );

  /// Start the TLS proxy server
  Future<void> start();

  /// Stop the TLS proxy server
  Future<void> stop();
}
